title: Bong Context
description: Technical notes by <a href="https://www.linkedin.com/in/pradipta-p-mitra/">Pradipta Mitra</a>
markdown: kramdown
timezone: America/New_York
permalink: /:categories/:year/:month/:day/:title/
theme: jekyll-theme-hacker
